<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2170b194-f7b0-4f7f-91a7-bca33190efa8</elementGuidId>
    <imagePath></imagePath>
    <name>button_seeMore</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="swiper-slide swiper-slide-next jss57747"] [class="MuiButtonBase-root MuiButton-root MuiButton-contained jss56067 undefined MuiButton-containedSizeSmall MuiButton-sizeSmall"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'generic-button-undefined') and equals(@type,'button') and equals(@text,'SEE MORE')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>generic-button-undefined</value>
        <webElementGuid>2bb5c710-1ef1-4594-b0df-7666d86f9dd9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>SEE MORE</value>
        <webElementGuid>2bb5c710-1ef1-4594-b0df-7666d86f9dd9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>2bb5c710-1ef1-4594-b0df-7666d86f9dd9</webElementGuid>
    </webElementProperties>
</WebElementEntity>