<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d1d59e29-ee3d-4944-a84e-73dd5d276ac0</elementGuidId>
    <imagePath></imagePath>
    <name>link_contacts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[4]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/admin/contacts') and equals(@text,'Contacts')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=banner &gt;&gt; internal:role=link &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/admin/contacts</value>
        <webElementGuid>7db495ac-e0ea-4416-9108-0174b96ede50</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contacts</value>
        <webElementGuid>7db495ac-e0ea-4416-9108-0174b96ede50</webElementGuid>
    </webElementProperties>
</WebElementEntity>