<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>03047d6a-d21d-4973-b58e-dfcad0a47cd0</elementGuidId>
    <imagePath></imagePath>
    <name>button_send</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root MuiButton-root MuiButton-contained jss12055 undefined MuiButton-containedSizeLarge MuiButton-sizeLarge"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'generic-button-undefined') and equals(@type,'submit') and equals(@text,'Send')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>form [data-testid="generic-button-undefined"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>generic-button-undefined</value>
        <webElementGuid>d1e17b6a-2fe5-43f0-ae18-1cb1a1634b2c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Send</value>
        <webElementGuid>d1e17b6a-2fe5-43f0-ae18-1cb1a1634b2c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>d1e17b6a-2fe5-43f0-ae18-1cb1a1634b2c</webElementGuid>
    </webElementProperties>
</WebElementEntity>