<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74b7d09d-584b-4aff-8a75-a4b86cd062ac</elementGuidId>
    <imagePath></imagePath>
    <name>input_selectAsubserviceSubProgramId</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/form[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#mui-52643</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'mui-52643') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid="form-select-subProgramId"] &gt;&gt; internal:label="Select a Subservice"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>mui-52643</value>
        <webElementGuid>cbcdfecb-0939-44e0-86cb-d27983044e21</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>cbcdfecb-0939-44e0-86cb-d27983044e21</webElementGuid>
    </webElementProperties>
</WebElementEntity>