<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe3a038f-4ff3-479b-aa3c-47b10ee1ecfa</elementGuidId>
    <imagePath></imagePath>
    <name>link_contacts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[4]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiBox-root jss11629"] &gt; [class="MuiListItem-root jss11590 MuiListItem-gutters"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/admin/contacts') and equals(@text,'Contacts')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=banner &gt;&gt; internal:role=link &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/admin/contacts</value>
        <webElementGuid>6309de21-6a17-4bdf-b1e8-119babdec272</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contacts</value>
        <webElementGuid>6309de21-6a17-4bdf-b1e8-119babdec272</webElementGuid>
    </webElementProperties>
</WebElementEntity>