<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba4ff2d8-faf7-4301-854e-2f67fbffd799</elementGuidId>
    <imagePath></imagePath>
    <name>item_mui74876Option0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'mui-33059-option-0')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=option &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>mui-33059-option-0</value>
        <webElementGuid>7efd09dc-c61b-443f-9d9b-68715829f232</webElementGuid>
    </webElementProperties>
</WebElementEntity>