<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>837710ed-1c32-46b0-935f-06dfb339950e</elementGuidId>
    <imagePath></imagePath>
    <name>item_option1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'mui-58861-option-1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=option &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>mui-58861-option-1</value>
        <webElementGuid>d33176e7-b4ad-432b-a616-a8594bb69086</webElementGuid>
    </webElementProperties>
</WebElementEntity>