<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fd1a4d76-d8b7-41db-88b2-cb7bbe4b587f</elementGuidId>
    <imagePath></imagePath>
    <name>th_requestNo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/table[1]/thead[1]/tr[1]/th[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Request No.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=columnheader[name="Request No."i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Request No.</value>
        <webElementGuid>f856e518-e3e5-4dcb-95ec-9a23db31eb16</webElementGuid>
    </webElementProperties>
</WebElementEntity>