<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5dca79ba-9f5c-4ec9-adce-3ce978ba7a9d</elementGuidId>
    <imagePath></imagePath>
    <name>th_requestNo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/table[1]/thead[1]/tr[1]/th[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Request No.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=columnheader[name="Request No."i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Request No.</value>
        <webElementGuid>2bb5c710-1ef1-4594-b0df-7666d86f9dd9</webElementGuid>
    </webElementProperties>
</WebElementEntity>