<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae2be686-44b6-4773-95fd-83a737e72553</elementGuidId>
    <imagePath></imagePath>
    <name>item_mui31940Option0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'mui-31940-option-0')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=option &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>mui-31940-option-0</value>
        <webElementGuid>2bb5c710-1ef1-4594-b0df-7666d86f9dd9</webElementGuid>
    </webElementProperties>
</WebElementEntity>