<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b7953e34-402e-401b-a233-fb57d88d8f41</elementGuidId>
    <imagePath></imagePath>
    <name>button_signIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'generic-button-undefined') and equals(@type,'button') and equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Sign In"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>generic-button-undefined</value>
        <webElementGuid>93241c17-9820-4178-bf0b-b477d0a09e9b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>93241c17-9820-4178-bf0b-b477d0a09e9b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>93241c17-9820-4178-bf0b-b477d0a09e9b</webElementGuid>
    </webElementProperties>
</WebElementEntity>